### PR TITLE
feat: improved Progress Bar

### PR DESCRIPTION
**Pull request by tuankhainguy**
PR for an improved Progress Bar
Deployment can be accessed from [Deployment](https://aiaprogressbar.netlify.app/)

aia-screenshot-1

aia-screenshot-2

## Feature
- Improved Progress Bar works like a slider

## Testing Methodology
- [x] Tested on [Netlify](https://aiaprogressbar.netlify.app/)
- [x] Tested on a Mac

## Checklist
- [x] Followed [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by tuankhainguy** [comment]
@Sraccity Ready for review

**Review by Sraccity — CHANGES_REQUESTED** [review]
**Question (Client)**: Did you check the design with the client?

Like did they visually see it? It seems bulky but workable so yeah

**Comment by tuankhainguy** [comment]
yes they said from a quick test it looked like just what they wanted

**Comment by Sraccity** [comment]
> yes they said from a quick test it looked like just what they wanted

Then, fine by me

**Review by Sraccity — APPROVED** [review]
**Praise**: Thanks for doing extra features

**Comment by Sraccity** [comment]
**Kudos**: Congrats on your PR

**Pull request merged**
